# Generated by Django 4.0.3 on 2022-06-30 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crypto',
            table=None,
        ),
    ]
